### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [mcb2003/blind-computing#13]
Hello! @mcb2003 

I am a graphic designer. I like to contribute opensource softwares.

I designed a logo for your repository. Please say me, what do you think about it. I will wait for feedback. Have a nice day!

![1](https://user-images.githubusercontent.com/36298335/44092555-714c749c-9fd9-11e8-85f9-906ebd8c7582.jpg)

**Comment by mcb2003** [comment]
hi @reallinfo
Thanks so much for your support, it couldn't be more apreciated, I'm thrilled that people like you are around to help small projects like this out.

Regarding the logo, I like it very much (using the obvious pun of bl eye ndcomputing). I'll have a think about it and wait to see if anyone else wants to chime in, otherwise, the logo spot is yours. Now then ... where should I put it?

**Comment by reallinfo** [comment]
Sure! Okay. I will send you a pr when the time comes. you can write to me whenever you want. I will make the change you want. I will wait for feedback. Have a nice day!

**Comment by mcb2003** [comment]
Actually, @reallinfo, I’ve had a few people look at the logo and everybody so far has recommended I use it. So I think that’s what I’m going to do. But I’m going to have to make some design decisions as to where I want to put it on the website first,  any suggestions are welcome of course (issue #14).

**Comment by reallinfo** [comment]
Hi again! I am sorry for my late answer. I sent all the necessary files and i updated the readme file. If there is a problem feel free to say me.

Please check the pr.

**Comment by mcb2003** [comment]
Hi  @reallinfo 
 Thank you so much, I’ve been very busy over the last week or so, so haven’t had time to do this.  But I’ll get working  now and accept your pull request.

**Comment by reallinfo** [comment]
You're If you have another request, you can write to me. Have a  nice day!

**Comment by mcb2003** [comment]
Everything has now been merged!
